### ISSUE TITLE
Promote the blog post as offical diesel guide

### ISSUE THREAD

**Issue by weiznich** [l4l/diesel-custom-types#1]
Thanks for the well written blog post :+1:

As a diesel maintainer I'm constantly looking for people willing to improve our guides. I think your blog post provides a good foundation for a guide about how to add support for custom types. It would be great to receive that as contribution either as [draft guide here](https://github.com/diesel-rs/diesel/tree/master/guide_drafts) (basically as it is) or as new [guide directly on the webpage here](https://github.com/sgrif/diesel.rs-website/) (Would need some minor rework to add some more information, can be discussed in a corresponding PR)

**Comment by l4l** [comment]
Thanks for reaching out, that sounds great to me, I would kindly share that work. Could you please (briefly) specify the necessary fixes (besides typos/grammar/etc) so I can estimate whether I have enough time for it?

**Comment by weiznich** [comment]
To note points that I've noticed while reading the post again:

# Major Points
* Skip the experimenting part at the beginning. The general structure should be: 
    1. Explain SqlType <-> Rust Type.
    2. Show the sql side type (migration)
    3. Implement the diesel sql type
    4. Configure diesel cli (maybe mention patch option here?)
    5. Implement `FromSql`/`ToSql` (mention that this depends on the actual use case)
    6. Other stuff (like `diesel-derive-enum`, but that should mention shortly that this is a third party crate and diesel does not expose this kind of API because of flexibility concerns)
* It should be mentioned somewhere that the process of adding support for arbitrary types is basically the same, as long as you own the rust side type. (Maybe linking to [`WriteTuple`](http://docs.diesel.rs/diesel/serialize/trait.WriteTuple.html)/[`Record`](http://docs.diesel.rs/diesel/pg/types/sql_types/struct.Record.html)?)

# Minor Points
* Link relevant doc's/guides for derives/configs/traits…
* `ToSql` impl should also be database specific, because that variant only works for postgres
* Shortly mention alternative strategies to implement `FromSql`/`ToSql` by forwarding to an existing impl (`<String as ToSql<Text, Sqlite>::to_sql("enum_value_as_string")`
* `AsExpression` is required for binding a value as expression of the specified `SqlType` in a query (just clarify that a bit)
* `ToSql` implements the conversation to the database specific transmit over wire format. It's a bit hard to write much about that, because that's at least for postgres/mysql not documented much... (Maybe find at least something here to link that's not libpq source code…)
* I'm not sure if the section about the upcoming change of the `RawValue` type is required. We would update the guide to match the 2.0 release later.

**Comment by l4l** [comment]
The first major point basically requires quite a lot of restructuring as I may assume. Therefore I would prefer sending it to the drafts and keeping an eye on it with further incremental improvements.

Opened a pr: https://github.com/diesel-rs/diesel/pull/2413, so I think we can continue there.
